### ISSUE TITLE
Unable to process file command 'output' successfully.

### ISSUE THREAD

**Issue by regorxxx** [dedene/curl#1]
Output is not working right and crashes.

>  [...]\,��6H=%�ީD�]�#)��y�˗S$p�I��n��H>=��Sh��y�K3
Error: Unable to process file command 'output' successfully.
Error: Invalid value. EOF marker missing new line.

```
      - name: "Get binaries"
        id: curl
        uses: dedene/curl@v1
        with:
          url: https://raw.githubusercontent.com/regorxxx/foobar2000-assets/main/Spider%20Monkey%20Panel/foo_spider_monkey_panel-v1.6.1-mod.fb2k-component
          args: -v
```
